input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  if "ERROR" in [message] {
    mutate {
      add_field => { "severity" => "high" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "springboot-app-logs-%{+YYYY.MM.dd}"
  }
}
