volumes:
  mongo-data:
  grafana-data:

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - "9093:9093"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

  mongodb-exporter:
    image: percona/mongodb_exporter:0.49
    container_name: mongodb-exporter
    command:
    - --mongodb.uri=mongodb://mongo:27017/mean_db
    - --collect-all
    ports:
      - "9216:9216"
    depends_on:
      - mongo


  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx/status
    ports:
      - "9113:9113"
    depends_on:
      - nginx

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx-reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
      
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
      
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
